spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

cors:
  origin: https://www.jeffersonminiwarehouses.com, https://jeffersonminiwarehouses.com


stripe:
  publishable:
  secret: ${STRIPE_SECRET_PROD}
