spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_site

cors:
  origin: https://www.jeffersonminiwarehouses.com, https://jeffersonminiwarehouses.com

stripe:
  publishable:
  secret: ${STRIPE_SECRET_PROD}
