spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_site
    username: user
    password: password

  # Stripe uses GSON instead of Jackson for JSON mapping
  # https://github.com/stripe/stripe-java/issues/307
  http:
    converters:
      preferred-json-mapper: gson

jwt:
  secret: ${STORAGE_SITE_JWT_SECRET}
  expiration: 28800000

stripe:
  publishable: pk_test_NpLxutjKOqdutIqGPyHkHyK300AMWKqV8o
  secret: ${STRIPE_SECRET_DEV}

cors:
  origin: http://localhost:3000

logging:
  level:
    com:
      zaxxer:
        hikari: WARN