apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service-deployment
spec:
  selector:
    matchLabels:
      app: storage-service
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: 192.168.1.23:5000/homelab/storage-service:latest
        env:
        - name: POSTGRES_URL
          value: "jdbc:postgresql://192.168.1.90:5432/matt"
        - name: POSTGRES_USER
          value: "matt"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: STORAGE_SITE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: storage-jwt
              key: secret
        - name: STRIPE_SECRET_DEV
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: dev
        - name: STRIPE_SECRET_PROD
          value: ""
        ports:
        - containerPort: 8080
      nodeSelector:
        default: "true"

