apiVersion: v1
kind: Service
metadata:
  name: storage-service-service
spec:
  type: LoadBalancer
  selector:
    app: storage-service
  loadBalancerIP: 192.168.1.65
  ports:
    - port: 80
      targetPort: 8080
